version: 2.1

executors:
  default:
    parameters:
      image:
        type: string
        default: node:10.15.3-alpine
        description: a image for docker container
    docker:
      - image: <<parameters.image>>
    environment:
      CHROME_BIN: /usr/bin/chromium-browser
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    working_directory: /nuxt-jest-puppeteer

commands:
  install_dependencies:
    steps:
      - run:
          # Run Puppeteer on Alpine
          # https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-on-alpine
          name: Install dependencies
          command: |
            apk update && apk upgrade && \
            apk add --no-cache \
                    udev \
                    ttf-freefont \
                    chromium

jobs:
  build:
    executor:
      name: default
    steps:
      - install_dependencies
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run: mkdir -p /nuxt-jest-puppeteer/test-results
      - run:
          name: run test
          command: npm test
      - store_test_results:
          path: /nuxt-jest-puppeteer/test-results
      - store_artifacts:
          path: /nuxt-jest-puppeteer/test-results
