version: 2.1

executors:
  default:
    parameters:
      image:
        type: string
        default: node:10.15.3-alpine
        description: a image for docker container
    docker:
      - image: <<parameters.image>>
    working_directory: /nuxt-jest-puppeteer

commands:
  install_dependencies:
    steps:
      - run:
          # Run Puppeteer on Alpine
          # https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-on-alpine
          name: Install dependencies
          command: |
            apk update && apk upgrade && \
            echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
            echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
            apk add --no-cache \
              chromium@edge \
              nss@edge \
              freetype@edge \
              harfbuzz@edge \
              ttf-freefont@edge

jobs:
  build:
    executor:
      name: default
    steps:
      - install_dependencies
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: run test
          command: npm test
